set(CMAKE_SYSTEM_NAME arm)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR arm)


set(CMAKE_C_COMPILER   /bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /bin/aarch64-linux-gnu-g++)


set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

#set(CMAKE_CROSSCOMPILING true)
#if(CMAKE_CROSSCOMPILING)
#  set(ENV{PKG_CONFIG_LIBDIR} ${CMAKE_FIND_ROOT_PATH}/lib/pkgconfig/)
#  include_directories(BEFORE ${CMAKE_FIND_ROOT_PATH}/include)
#endif()

